# Generated by Django 2.1.2 on 2018-10-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawledpages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField(db_index=True)),
                ('url', models.URLField()),
                ('is_seed_url', models.BooleanField(db_index=True, default=False)),
                ('content', models.TextField(null=True)),
                ('page_links', models.TextField(null=True)),
                ('image_links', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
